try {
    someMethod()
} catch {
    console.log('エラー')
}

// エラー時の変数を省略しない今までの書き方
// try {
//     someMethod()
// } catch(err) {
//     console.log('エラー')
// }
